# Generated by Django 5.0.1 on 2024-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhar_number", models.BigIntegerField(unique=True)),
                ("mobile_number", models.BigIntegerField(unique=True)),
                ("age", models.PositiveIntegerField()),
            ],
        ),
    ]
