# Generated by Django 5.0.1 on 2024-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_yourmodel_primaryvoterdatabase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Official",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FULLName", models.CharField(max_length=100)),
                ("Username", models.CharField(max_length=50, unique=True)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Aadhar_Number", models.CharField(max_length=12, unique=True)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
