# Generated by Django 5.0.1 on 2024-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_remove_official_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="primaryvoterdatabase",
            name="face_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="voter_images/primary/"
            ),
        ),
        migrations.AddField(
            model_name="secondaryvoterdatabase",
            name="face_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="voter_images/secondary/"
            ),
        ),
    ]
