# Generated by Django 5.0.1 on 2024-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_remove_primaryvoterdatabase_face_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="official",
            name="mobile_number",
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
