# Generated by Django 5.0.1 on 2024-03-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_alter_official_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="official",
            name="mobile_number",
        ),
    ]
